@startuml "Parking Lot: Sequence Diagram"

actor Driver
actor Vehicle
participant "Parking Manager" as M
participant Camera as C
participant Slot as S
participant Gate as G

activate M
activate C
activate G


M -> S : Initilize
activate S

group Entering the parking lot
Vehicle -> C : Approching the gate
C --> Vehicle : Scan 
C --> M : Provide Plate# and Height
end

M -> M : Check for vehicle height
alt allowed to enter

M -> M : Check for available slot
alt available 

M -> G : Open

Driver -> S: Park
S -> M: Reserved
Driver -> S: Depart
S-> M: Clear

group Exiting the parking lot
Vehicle -> C: Approching the gate
C --> M: Provide Plate#
M --> Driver: Ask for Payment
end

group Payment
Driver -> M: Pay
M --> G: Open
rnote over G: wait 5 sec
G -> G: Close
end

else 
M --> Driver: Display "Parking is full!"
end 

else 
M --> Driver: Display "You are not allowed to enter!"

end

@enduml